"""Resumable orchestration, injected strategies, generators and audio assembly."""
import hashlib
import json
import shutil
import subprocess
import uuid
from pathlib import Path
from .strategies import EDITOR, clean, text_result
from api.services.reading_reduction import prepare, word_count

VERSION = "production-1"


def split_audio(text, limit):
    """Bounded chunks, preserving every source character exactly."""
    while text:
        end = min(len(text), limit)
        if end < len(text):
            boundary = text.rfind(" ", 0, end)
            if boundary > end // 2:
                end = boundary + 1
        yield text[:end]
        text = text[end:]


class FFmpegAssembler:
    @staticmethod
    def available():
        return bool(shutil.which("ffmpeg") and shutil.which("ffprobe"))

    def combine(self, files, destination):
        # Paths are generated by the app, never book titles or user filenames.
        manifest = destination.with_suffix(".concat.txt")
        manifest.write_text("\n".join("file '" + str(p.resolve()).replace("\\", "/").replace("'", "'\\''") + "'" for p in files), encoding="utf-8")
        subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-f", "concat",
                        "-safe", "0", "-i", str(manifest), "-c", "copy", str(destination)],
                       check=True, capture_output=True, timeout=180)
        output = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1", str(destination)],
            check=True, capture_output=True, text=True, timeout=30)
        return float(output.stdout.strip())


class CachedGenerator:
    def __init__(self, provider, recorder, folder, check):
        self.provider, self.recorder, self.folder, self.check = provider, recorder, folder, check
        folder.mkdir(parents=True, exist_ok=True)

    def __call__(self, phase, system, payload, validate=None):
        self.check()
        key = hashlib.sha256(json.dumps([VERSION, self.provider.name, self.provider.model, phase,
                                         system, payload], ensure_ascii=False, sort_keys=True).encode()).hexdigest()
        path = self.folder / (key + ".json")
        if path.exists():
            result = json.loads(path.read_text(encoding="utf-8"))
            if validate:
                validate(result)
            self.recorder.cache_hit(phase)
            return result
        reply = self.recorder.run(phase, self.provider, lambda: self.provider.generate(system, payload))
        self.check()
        result = json.loads(reply.content)
        if not isinstance(result, dict):
            raise ValueError("Das Modell hat kein JSON-Objekt geliefert")
        if validate:
            validate(result)
        temporary = path.with_suffix("." + uuid.uuid4().hex + ".tmp")
        temporary.write_text(json.dumps(result, ensure_ascii=False), encoding="utf-8")
        temporary.replace(path)
        return result


class BookPipeline:
    def __init__(self, strategies, generate, audio, recorder, assembler, folder, progress, check, save_text):
        self.strategies, self.generate, self.audio = strategies, generate, audio
        self.recorder, self.assembler, self.folder = recorder, assembler, folder
        self.progress, self.check, self.save_text = progress, check, save_text

    def run(self, chapters, options):
        self.check()
        if not chapters or not any(c["text"].strip() for c in chapters):
            raise ValueError("Die ausgewählten Kapitel enthalten keinen auslesbaren Text")
        if options["audio"] and not self.assembler.available():
            raise ValueError("Für Audio werden ffmpeg und ffprobe benötigt")
        source_words = sum(word_count(c["text"]) for c in chapters)
        options = {**options, "core_words": min(options["core_words"], source_words)}
        warnings = []
        if options["strategy"] == "original":
            _, blocks = prepare(chapters, block_limit=900)
            sections = [{"source_id": f"s{i}", "href": chapters[b["chapter"]]["href"],
                "title": b["title"], "text": b["text"], "source_text": b["text"]} for i, b in enumerate(blocks)]
            label = "Original"
        else:
            strategy = self.strategies.get(options["strategy"])
            sections, warnings = strategy.reduce(chapters, options, self.generate, self.progress)
            label = strategy.label
        if options["language"] != "original":
            for i, section in enumerate(sections):
                self.progress(round(65 + 15 * i / len(sections)), f"Übersetze Abschnitt {i + 1} von {len(sections)}")
                answer = self.generate("translation", EDITOR, {"language": options["language"],
                    "title": section["title"], "text": section["text"],
                    "task": "Translate all this passage as a professional literary translator. "
                        "Use idiomatic language and locally natural idioms, preserve facts, tone, "
                        "examples and paragraph structure. Do not summarize or add content. "
                        "Return {text:..., title:...}."}, text_result)
                section["pre_translation_text"] = section["text"]
                section["text"] = clean(answer["text"])
                section["title"] = clean(answer.get("title") or section["title"])
        count = sum(word_count(s["text"]) for s in sections)
        result = {"strategy": options["strategy"], "label": label, "language": options["language"],
            "target_ratio": options["ratio"] if options["strategy"] == "reading" else None,
            "source_words": source_words, "word_count": count, "actual_ratio": count / source_words,
            "estimated_minutes": round(count / 150), "warnings": warnings,
            "quality_status": "not_editorially_reviewed", "sections": sections, "audio": []}
        # Persist usable text before starting speech, so an audio failure does not lose it.
        self.save_text(result)
        if options["audio"]:
            chunks = []
            for section in sections:
                chunks.extend(split_audio(section["text"], self.audio.max_characters))
            files = []
            self.folder.mkdir(parents=True, exist_ok=True)
            for i, chunk in enumerate(chunks):
                self.check()
                self.progress(round(80 + 17 * i / len(chunks)), f"Vertone Abschnitt {i + 1} von {len(chunks)}")
                digest = hashlib.sha256((self.audio.name + self.audio.model + options["voice"] + chunk).encode()).hexdigest()
                path = self.folder / (digest + ".mp3")
                if path.exists() and path.stat().st_size:
                    self.recorder.cache_hit("audio")
                else:
                    temporary = path.with_suffix("." + uuid.uuid4().hex + ".partial.mp3")
                    self.recorder.run("audio", self.audio, lambda: self.audio.generate(chunk, options["voice"], temporary))
                    self.check()
                    temporary.replace(path)
                files.append(path)
            self.check()
            self.progress(98, "Verbinde das Hörbuch")
            destination = self.folder / ("audiobook-" + uuid.uuid4().hex + ".mp3")
            duration = self.assembler.combine(files, destination)
            result["audio"] = [{"path": str(destination), "duration_seconds": duration}]
        return result
